### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by WyvernX-YT** [Eman49exe/Simple-Hello-World-#1]
This is youtube tutorial code

**Comment by Eman49exe** [comment]
> This is youtube tutorial code

I did follow along a tutorial, this is me messing around in vscode 2019 I am sorrta new to C++ (Started learning like a month ago) leave me alone toxic java dev

**Comment by Eman49exe** [comment]
> This is youtube tutorial code

No I made this myself its quite simple

Just using a namespace so I dont need to use std::
and and a simple cout function there is no need for a tutorial to learn somthing this simple
